name: CI CD Pipeline

on:
  push:
     branches:
        - main

jobs:
   build-and-deploy:
       runs-on: ubuntu-latest

       steps:
        - name: checkout repository
          uses: actions/checkout@v3

        - name: setup docker buildx
          uses: docker/setup-buildx-action@v3

        - name: docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.docker_username }}
            password: ${{ secrets.docker_password }}

        - name : docker build and push
          uses: docker/build-push-action@v5
          with:
             push: true
             tags: asomaaroufiniyaa/node_app:latest


        - name: ssh to AWS and run container
          uses: appleboy/ssh-actions@v0.1.7
          with:
            host: ${{ secrets.AWS_Host }}
            username: ubuntu
            key: ${{ secrets.AWS_Key }}

            script: |
              sudo apt update 
              sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker compose plugin
              docker pull asomaaroufiniyaa/node_app:latest
              docker stop my-website || true
              docker rm my-website || true
              docker run -d -p 2020:80 --name my-site asomaaroufiniyaa/node_app:latest
          
            
